name: Svelte Check

on:
  push:
    paths:
      - '**.svelte'
      - '**.ts'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11.25.0

      - name: Set up Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.20.0
          cache: 'pnpm'

      - name: Prepare blank env file
        run: cp .env.example .env

      - name: Install dependencies
        run: pnpm ci

      - name: Add Svelte Check annotator
        uses: prgm-dev/svelte-check-pr-annotator@91bbcab7428265bde6223fd1fa824336af7ef488 # main

      - name: Run Svelte Check
        run: pnpm run check --output machine
