name: Svelte Check

on:
  push:
    paths:
      - '**.svelte'
      - '**.ts'
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          version: 11.10.0

      - name: Set up Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24.18.0
          cache: 'pnpm'

      - name: Prepare blank env file
        run: cp .env.example .env

      - name: Install dependencies
        run: pnpm ci

      - name: Add Svelte Check annotator
        uses: prgm-dev/svelte-check-pr-annotator@91bbcab7428265bde6223fd1fa824336af7ef488 # main

      - name: Run Svelte Check
        run: pnpm run check --output machine
